spring.application.name=measurement-service
server.port=8082

jwt.secret=quantityMeasurementAppSecretKeyForOAuth2JWT2024LongEnough

history.service.url=http://localhost:8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
