spring.application.name=eureka-server
server.port=8761

# Eureka server khud apne aap ko register nahi karega
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dashboard URL
eureka.server.enable-self-preservation=false
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
